### ISSUE TITLE
Preparing the next major release of terra-ui

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-ui#117]
It's been a while since we cut a major release holistically across all terra ui components. There are some non-passive changes needed in terra-ui components like terra-base and terra-i18n that will require a major version bump for all components.

We want to communicate these changes as well as other non-passive changes that we are considering across terra-ui. At this time, we are planning to cut a new major release involving terra-base and terra-i18n around then end of March 2019. We are planning to release some other major version bumps to individual packages are the updates become available.

## Terra Core Updates planned for end of March 2019 Release

PR for this set of work: https://github.com/cerner/terra-core/pull/2288

- [x] [Switch locale prop to be required on terra-base component](https://github.com/cerner/terra-core/issues/1149)
- [x] [Update codesplitting in terra-i18n to use dynamic imports](https://github.com/cerner/terra-core/issues/1720)
- [x] [Remove post install script from terra-i18n](https://github.com/cerner/terra-core/issues/1941)
- [x] [Remove aggregate-translations script from terra-i18n](https://github.com/cerner/terra-core/issues/1940)
- [x] [Improve usage of passed along react-intl modules](https://github.com/cerner/terra-core/issues/1982)
- [x] [Update react to latest stable release](https://github.com/cerner/terra-core/issues/2287)
- [x] [Add ability to render layout at full page height](https://github.com/cerner/terra-framework/issues/124)

## Additional Terra Core Updates (Post March 2019 MVB release)
- [x] [[terra-responsive-element] Issue with repetitive resizing](https://github.com/cerner/terra-core/issues/1891)
- [x] [[terra-responsive-element] Consume terra-breakpoints and update size props](https://github.com/cerner/terra-core/issues/2048)
- [x] [Update Grid to consume terra-breakpoints package](https://github.com/cerner/terra-core/issues/2131)
- [x] [Update react-focus-trap dependency to latest version in terra-overlay](https://github.com/cerner/terra-core/issues/2280)
- [x] [[terra-status-view] Remove opt object and add proptype check](https://github.com/cerner/terra-core/issues/2178)
- [x] [Replace customStatusColor prop from Terra Alert](https://github.com/cerner/terra-core/issues/2307)

## Terra Framework  Major Version Bump changes (Post March 2019 MVB release)
- [x] [Does not honor time in maxDateTime](https://github.com/cerner/terra-framework/issues/524)
- [x] [Create/expose consolidated 'onBlur' for date-time-picker](https://github.com/cerner/terra-framework/issues/522)
- [x] [Update to react-router v5](https://github.com/cerner/terra-framework/issues/552)

## Terra Toolkit Major Version Bump Proposal
https://github.com/cerner/terra-toolkit/issues/262

## Terra Dev Site Major Version Bump changes
- [x] [Update dependencies to latest stable releases (Babel 7, PostCSS)](https://github.com/cerner/terra-dev-site/issues/103)
- [x] [Remove Global Wdio Refresh](https://github.com/cerner/terra-dev-site/issues/136)
- [x] [Remove terra-app-delegate dependency](https://github.com/cerner/terra-dev-site/issues/138)

**Comment by emilyrohrbough** [comment]
Terra-Dev-Site will need to do a MVB of terra-toolkit in it's MVB as well.

**Comment by bjankord** [comment]
OCS theme updates that require major version bumps on components that we know about are documented on this issue: https://github.com/cerner/terra-ui/issues/121

The OCS theme updates that require major version bumps will be rolled out separately from the major version bumps noted on [this issue](https://github.com/cerner/terra-ui/issues/117).

**Comment by mjhenkes** [comment]
**Proposal:** 
Remove color prop from terra-text and terra-heading due to causing the inability to theme the component. (Do we have any other color props in our components that should be removed?)

**Comment by emilyrohrbough** [comment]
Toolkit v5.0.0 Proposed Changes :  https://github.com/cerner/terra-toolkit/issues/262

**Comment by emilyrohrbough** [comment]
This change would be great to get into the next MVB of terra-dev-site: https://github.com/cerner/terra-dev-site/issues/136
